### ISSUE TITLE
Model variants of Wang et al. (2014) MEE

### ISSUE THREAD

**Issue by aminorberg** [dwarton/mvabund#104]
Hi,

Would it be possible to get an example code for fitting the three model variants in Brown et al. (2014) (e.g. Fig. 4) with the current R package?

Best regards,

Anna

**Comment by dwarton** [comment]
Hello!
I guess you mean Brown et al 2014?  Something along the lines of:
```
trait.env = traitglm(abund, env, trait, method="cv.glm1path")
spp.env = traitglm(abund, env, method="cv.glm1path")

trait$spp = factor(1:nrow(trait))
traitPlusSpp.env = traitglm(abund, env, trait, method="cv.glm1path")
```

**Comment by aminorberg** [comment]
Hi David! Yes, I of course meant that, sorry. Was reading both intensively, hence the mixup :D Thank you for your answer, that cleared things up.
