### ISSUE TITLE
Issue with Lasso Penalty

### ISSUE THREAD

**Issue by mthompson89** [dwarton/mvabund#105]
Hello, 
I was following a tutorial for running an RQL analysis with mvabund (here: https://heather-grab.github.io/Entom-4940/rql.html ) and everything works fine until I try and run a lasso penalty using `method = "glm1path"` when I run the model with this method I get the error
```
Error in while (dev.change < (-tol[1]) & half.step < 4) { : 
  missing value where TRUE/FALSE needed
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```
some digging I think the issue is somewhere in the `glm1()` function where `likes` is `NA` which in turn causes dev.change to be `NA` and the `while` loop of `while(dev.change<(-tol[1] & half.step<4)` doesn't evaluate to `TRUE/FALSE`.  I am not sure, but I think `likes` is `NA` because `res` is `NA` after running `res = mu.update(b.lasso,y,X,weights,family,is.nb,phi.int,lambda,init=T,tol=tol)`

any help you could provide would be greatly appreciated!

**Comment by fontikar** [comment]
@dwarton I wasn't able to recreate the exact error, the code breaks when fitting a model with `traitglm()` so not exactly where @mthompson89 has said above. 

I'm using  mvabund_4.2.2 and using the same tutorial as @mthompson89 (https://heather-grab.github.io/Entom-4940/rql.html)

Here are the errors I am getting: 
```# Error in x - xbar : non-numeric argument to binary operator
# In addition: Warning messages:
# 1: In get_polys(Q) :
#   Binary variable 'Sociality' found and changed to a factor
# 2: In get_polys(Q) :
#   Binary variable 'Parasitic' found and changed to a factor
# 3: In mean.default(x) : argument is not numeric or logical: returning NA
```
The code breaks on line 46 in the `get_poly()` function on this particular line: 
```poly(X[, i.quant], degree = 2, coefs = X.des.train$coefs[[i.quant]])
Error during wrapup: non-numeric argument to binary operator
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
```

Code to reproduce the error can be found here: https://www.dropbox.com/s/iz59so0ai7jqw0w/RQL_vignette.Rmd?dl=0

**Comment by dwarton** [comment]
v4.2.3 addresses Fonti's issue (by changing character vectors to factors in the code) but I can't reproduce the original error...
