### ISSUE TITLE
Composition data analysis 

### ISSUE THREAD

**Issue by chochart** [dwarton/mvabund#107]
Hello, 

I attempt to conduct generalized linear model for a microbiome dataset (16S HTS). Given that microbiome dataset is compositional, as shown in Gloor et al. (2017, https://doi.org/10.3389/fmicb.2017.02224), I was wondering, what is the right and better way to test hypotheses about the community-environment association. 

I would like to use the R package mvabund, but the examples and documentation did not provide clues on how to process compositional data.

Do you have any feedbacks or recommandations, on how process compositional data with mvabund ? 

Thanks a lot ! 

Corentin

**Comment by dwarton** [comment]
hey there,
I would suggest adding an offset to the model to deal with this.  Attached are some notes from my upcoming text which might help - if you have microbiome data (I am assuming many columns) I would go for the quick-and-dirty option (section 14.3.1)
[compMvabund.pdf](https://github.com/aliceyiwang/mvabund/files/9177108/compMvabund.pdf)

**Comment by chochart** [comment]
Hey dwarton ! 
You assume right. I got many columns (Amplicon Sequence Variant) and more than rows (Sample). I will test that ! 
Thanks a lot ! 
Corentin
