### ISSUE TITLE
Univariate tests in pairwise comparison

### ISSUE THREAD

**Issue by camillethuyentruong** [dwarton/mvabund#109]
Hi and thank you for putting together this great package!

I am testing how the abundance in 20 fungal genera varies between three different tree species, in 15 sites that are either mixed (two tree species present) or pure (one tree species present):

```
data = data.frame(abund_table,env_table)
abu = mvabund(data[,1:20])

# Response variable as % relative abundance instead of count
total <- apply(abu, 1, sum)
data$logtotal <- log(total)

# Multivariate test
mod_tree = manyglm(abu ~ factor(data$TreeSpecies),
                  data=data, family = 'negative binomial', offset=data$logtotal)
test = anova.manyglm(mod_tree, p.uni = "adjusted", pairwise.comp = data$TreeSpecies)
test$uni.p
test$pairwise.comp.table
```
`test$pairwise.comp.table` does not include univariate tests and `test$uni.p` gives the fungal genera that vary significantly according to the tree species factor, but not in between each tree species in particular.

Is there a way to do this? (i.e. genus A is significantly different between tree species 1 and tree species 2)

**Comment by dwarton** [comment]
thanks for your message :)
Unfortunately, the package doesn't currently do this, if you wanted pairwise comparisons on genus A you would need to run a model on genus A only.
