### ISSUE TITLE
Uniqual visits /offset

### ISSUE THREAD

**Issue by PauLucio** [dwarton/mvabund#116]
Dear all,

I have a question I would like to address, I am sure most of you have encountered the same problem. We are studying the pollinator assemblage of three related plants from 6 plots, in each plot, we have 3 plants (1 plant per species). So, every row of our file represents an insect survey visiting one plant.
  
The effort has been very similar 13 or 14 visits per plant during one spring/summer, so we can consider the effort almost constant. However, there are a significant number of visits (5-8 depending on the plant) in which no insects were recorded. So, we have a large amount of 0's. I was wondering if deleting these rows (the rows with no insects were recorded) would be inappropriate for the analysis. I have checked the residuals and they fit pretty well a binomial distribution after removing the mentioned rows. If this would be the best approach, then the rows (visits) would be unequal, so I think would need to use a log(number of visits, i.e. rows per species) as an offset. 

Thanks for any advise

**Comment by dwarton** [comment]
I would recommend keeping these empty rows in the dataset - if you delete them you are biasing your estimates of abundance to be higher than they should be.  Having lots of zeros in your data doesn't really affect the analysis, except maybe sometimes by slowing down convergence, but I see no major problem having the zeros there but arguably you are introducing a problem if you remove them.

**Comment by PauLucio** [comment]
Many thanks David, I appreciate your advice
