### ISSUE TITLE
How to add a random effect when using traitglm() function?

### ISSUE THREAD

**Issue by Breezy25** [dwarton/mvabund#119]
Hi, I want to use the fourth-corner model to test the trait-environment relationships. My data has a nested sampling design so that some plots are spatially correlated. I want to account for this effect by adding the **site** as a random effect in the model (as one would do in the mixed-effect model). 

Below is copied from the description in the traitglm() function:
"If using penalised likelihood (as in glm1path and cv.glm1path) or **a random effects model**, by all means include main effects as well as row/column effects, and the penalties will sort out which terms to use"

If I understand it correctly, the traitglm() function can handle mixed-effect (random effects) models? But I am struggling to use it correctly.

I tried to modfiy the example code as below, but it did not work:

ft1=traitglm(antTraits$abund,
             **cbind(antTraits$env[,3:4],site = rep(c('a','b','c'),10))**,
             antTraits$traits[,c(1,3)],
             formula=~Shrub.cover:Femur.length+Shrub.cover:Pilosity **+ (1|site)**,composition=TRUE,method="glm1path")

Error in 1 | site : 
  operations are possible only for numeric, logical or complex types

Looking forward to your response! Thank you in advance!

Best,
Yuhao

**Comment by dwarton** [comment]
(1|site) notation doesn't work with the glm1path function.  It might not work at all with traitglm, not sure if I tested that.  If interested in testing for a trait-environment relationship (i.e. intending to use an anova call on your traitglm object) then I would recommend fitting a model using gllvm or glmmTMB.  Using glmmTMB you could use the rr structure to include a latent variable in your model to account for correlation.  Some of the work you would need to do to prepare your data for glmmTMB (which takes data in long format) could actually be done by a traitglm call, if you look in ft1$data (well, for a model that didn't return an error!).  e.g. the below might be a good start
`library(mvabund)
data(antTraits)
ft=traitglm(antTraits$abund,antTraits$env[,1:3],antTraits$traits[,1:3],col.intercepts=FALSE)
str(ft$data)

longData=ft$data
names(longData)[1]="abund"
str(longData)

# doesn't have main effects for traits, add those
longData$Femur.length = antTraits$traits$Femur.length[rep(1:ncol(antTraits$abund),each=nrow(antTraits$abund))]
# add spp and site codes
longData$spp=rep(names(antTraits$abund),each=nrow(antTraits$abund))
longData$site=rep(rownames(antTraits$abund),ncol(antTraits$abund))


library(glmmTMB)
ftLV=glmmTMB(abund~(1|spp)+poly(Bare.ground,2)+poly(Femur.length)+Bare.ground:Femur.length+rr(0+spp|site,2), data=longData, family=poisson())
summary(ftLV)
`

**Comment by Breezy25** [comment]
Dear David, Thank you so much for your patient reply! I will think about your suggestions.
