### ISSUE TITLE
summary.manyglm fails if family is "binomial(link=logit)"

### ISSUE THREAD

**Issue by raymondben** [dwarton/mvabund#20]
Fails:
[from the demo code]

> glm.spid.bin <- manyglm(pres.abs~soil.dry+bare.sand+moss, data=X, family="binomial")
> summary(glm.spid.bin)

Error in summary.manyglm(glm.spid.bin) : 
  'family' not defined. Choose one of 'poisson', 'negative.binomial', 'binomial' for an manyglm object

The family is:

> glm.spid.bin$family
> [1] "binomial(link=logit)"

But summary.manyglm looks for an exact string match on the family (object$family == "binomial"), so it fails. Probably this test should be more like the one used in anova.manyglm (substr(object$family, 1, 1) == "b")

> sessionInfo()
> R version 3.2.2 (2015-08-14)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base  
> other attached packages:
> [1] mvabund_3.11.5

**Comment by aliceyiwang** [comment]
Hi, Ben,

I don't get the error in summary.manyglm(glm.spid.bin) by running the
example. I'm not sure which version you are looking at, but the line
(substr(object$family,
1, 1) == "b") is not in anova.manyglm() on GitHub. In fact, the substring
function is used only in manyglm() to parse the input argument 'family' to
object$family. Both summary and anova functions inherit the object's family
class from object$family. Therefore, unless the attribute is manually
altered, you should not get the error with summary.manyglm or
anova.manyglm. Please let me know if there are still problems.

Alice

**Comment by raymondben** [comment]
We were using the CRAN version (3.11.5, see my sessionInfo output above). You're right, the current dev version (3.11.7) doesn't have this problem. Sorry, didn't check that before submitting. Thanks.

**Comment by eddelbuettel** [comment]
Thanks for the follow-up.  Maybe time for Alice to roll up a new version...

**Comment by aliceyiwang** [comment]
David,

Maybe it is time to update the CRAN version?

Thanks,
Alice

On Mon, Mar 21, 2016 at 5:59 AM, Dirk Eddelbuettel <notifications@github.com
