### ISSUE TITLE
summary P-value calculation

### ISSUE THREAD

**Issue by dwarton** [dwarton/mvabund#25]
bootstrap P-values in summary.manyglm and summary.manylm are computed as (# resampled stats >= observed stat) / nBoot rather than (# resampled stats >= observed stat + 1) / ( nBoot +1).  The latter is preferred, but is currently only implemented in summary for perm.resid, please fix.

**Comment by aliceyiwang** [comment]
The adjustment is already done for summary.manyglm. Please see line 222 - 224 in function GlmTest::summary() of glmtest.cpp.

**Comment by dwarton** [comment]
I think you mean lines 232-234.  OK, great!  But what about summary.manylm?

**Comment by dwarton** [comment]
If I do the following:
  example(summary.manyglm)
  summary(glm.spid, resamp="monte.carlo", test="wald",nBoot=9)
I get P-values that have been divided by 9 not 10 so something is still wrong...

Similarly for manylm
  example(summary.manylm)
  summary(fit, cor.type="shrink", p.uni="adjusted", nBoot=9)

whereas anova.manylm is fine:
  example(anoiva.manylm)
  anova(fit, fit0, fit1, fit2, nBoot=9, test="F", p.uni="adjust")
gives P-values to one decimal place only ie they were clearly divided by 10 as is desired

**Comment by aliceyiwang** [comment]
Alright, the problem was due to nboot=nBoot-1 in summary.manyglm.R. Don't
know why nBoot-1 was passed. Anyway, it is fixed now. The +1 adjustments
are done for the manylm test functions as well. Please check the updated
version. Ta!

**Comment by eddelbuettel** [comment]
Shall we make a new release?  At least [someone on StackOverflow](http://stackoverflow.com/questions/36766560/r-package-install-from-github-error-and-warning) is confused about how to install from here.   We could also set up a [drat](http://dirk.eddelbuettel.com/code/drat.html) repository or use one of the ones I have; [this one](http://ghrr.github.io/drat/) is meant to be for general use.

**Comment by dwarton** [comment]
No the problem has not yet been fixed.
summary.manylm and summary.manyglm now look fine but anova.manylm now uses nBoot+2 as its denominator!
Yes we could do a new release but maybe what we need is installation instructions on github - I gather the problem is GSL related?

**Comment by eddelbuettel** [comment]
Good point.  We can maybe "just" provide a Windows binary via this [ghrr drat](http://ghrr.github.io/drat) and point to it?   I sometimes do that with other pre-releases.

**Comment by aliceyiwang** [comment]
There was an odd line of nBoot=nBoot+1 in anova.manylm.R. The new build
should works now.

Thanks,
Alice.

**Comment by dwarton** [comment]
yep, super.  thanks
