### ISSUE TITLE
BootID with case resampling- bug in implementation of offset

### ISSUE THREAD

**Issue by EveSlavich** [dwarton/mvabund#29]
When doing an anova using a randomly generated (independent and identically distributed) BootID matrix, with resamp= "case", the p-values are all around 0.5. If no BootID is used, p-values on the same data are 0.001. This suggests that when BootID argument is supplied, the offset is not being implemented correctly. 

CODE TO REPLICATE BELOW:

rm(list=ls())

set.seed(42)
# simulate some rough and ready play data
# co-ords

x = runif(500)
y = runif(500)
# covariates

library(RandomFields)
temperature = RandomFields::RFsimulate(model = RandomFields::RMexp(var=1, scale=0.1),
                                       x=x, y=y,grid=F,n=1)$variable1
#20 species

nspec = 20
responseMultiSpecies = matrix(nrow=500, ncol=nspec)
Beta_multi = rnorm(nspec,10,1)

for (j in 1:nspec){
  spatial_residuals4 = RandomFields::RFsimulate(model = RandomFields::RMexp(var=1, scale=0.05),
                                                x=x, y=y,grid=F, n=1)$variable1
  responseMultiSpecies[,j] = temperature*Beta_multi[j] + spatial_residuals4 + rnorm(500)
  responseMultiSpecies[,j]=rbinom(n=500, size=1, prob=exp( responseMultiSpecies[,j])/c(1+ exp(responseMultiSpecies[,j])))
}

multispecies_dat=data.frame(responseMultiSpecies, temperature)

library(mvabund)

responseMultiSpecies=mvabund(multispecies_dat[,1:20]) #20 species multivariate reponse
# models

mod.1  = manyglm(responseMultiSpecies~1, data = multispecies_dat,family="binomial")
mod.2  = manyglm(responseMultiSpecies~temperature, data = multispecies_dat,family="binomial")
# IID boot ID matrix

bootID_IID = matrix(sample(1:500,500*1000,replace=T),nrow=1000,ncol=500)
# anova's

mvabund.case.bootID.0 = anova(mod.1, mod.2, resamp="case",bootID=bootID_IID)
mvabund.case.bootID.none = anova(mod.1, mod.2, resamp="case")
# With a boot ID matrix, the p value is close of 0.5

mvabund.case.bootID.0$table
# Without a boot ID matrix, the p value is close to 0.001

mvabund.case.bootID.none$table
# try it a number of times (warning ~30 minute running time)

mvabund.case.bootID.0_ = c()
mvabund.case.bootID.none_ = c()
for (i in 1:50){
bootID_IID = matrix(sample(1:500,500*1000,replace=T),nrow=1000,ncol=500)
# anova's

mvabund.case.bootID.0_[i] = anova(mod.1, mod.2, resamp="case",bootID=bootID_IID)$table[2,4]
mvabund.case.bootID.none_[i] = anova(mod.1, mod.2, resamp="case")$table[2,4]
}
# Summary : with bootID argument p - values from 0.5025 - 0.5714, mean 0.5357.
# Summary: without bootID argument p - values all 0.001

**Comment by aliceyiwang** [comment]
Hi, Eve,

Thanks for pointing it out. I will have a look at the problem asap in the
next few days.

Alice

**Comment by aliceyiwang** [comment]
Hi, Eve,

The bug is fixed. Please check the updated package 3.11.11 on GitHub.

Regards,
Alice

**Comment by EveSlavich** [comment]
Thank you so much Alice! Hope all is well with you and Rayanne (sorry if I
spelled it wrong).

Eve
ᐧ
