### ISSUE TITLE
manylm not accepting input bootID

### ISSUE THREAD

**Issue by dwarton** [dwarton/mvabund#31]
example(anova.manylm)
bootid = matrix(NA,4,28)
for(i in 1:4)
{  
  bootid[i,1] = i
  bootid[i,2:28] = (1:28)[-i]
}
anova(fit,bootID=bootid)
anova(fit,bootID=as.numeric(bootid))
# note in contrast that manyglm has the appropriate behaviour

**Comment by aliceyiwang** [comment]
Fixed. Please check. Thanks, Alice.
