### ISSUE TITLE
File src/mvabund_types.h now creates problems for Rcpp

### ISSUE THREAD

**Issue by eddelbuettel** [dwarton/mvabund#43]
mvabund uses what was once a "pre-release" of the `Rcpp::Nullable<>` class in `src/mvabund_types.h`.

Rcpp itself now has a slightly newer version, and including both now leads to errors.

In order to sort this out, I would suggest to simply rely on Rcpp alone.  I have verified that mvabund then build fine. 

We can either just remove `src/mvabund_types.h`, or keep it around (if we every need it again) but keep it empty. I would be happy to prepare a corresponding pull request for either option.

With best wishes for 2017,   Dirk

**Comment by eddelbuettel** [comment]
Happy New Year.  

Any chance that 'team mvabund' could comment on this?  And/or make the change I proposed in #44 ?

**Comment by aliceyiwang** [comment]
Hi, Dirk, Happy New Year!

I am currently in a job transition. I will get back to you later asap.

Thanks,
Alice

**Comment by eddelbuettel** [comment]
Happy New Year to you too, and congratulations on any pending changes -- I am sure they are exciting!  

As I recall David last acted as maintainer so we would need him CRAN changes.  Sorry again to be forcing a change, but the initial testing if the `Rcpp::Nullable<>` here was really invaluable.
