### ISSUE TITLE
Update .travis.yml

### ISSUE THREAD

**Issue by eddelbuettel** [dwarton/mvabund#59]
I noticed that the `.travis.yml` file is a little stale, and would like to suggest two changes:
- update to what I currently use (see any of my repos, eg [here for RcppGSL](https://github.com/eddelbuettel/rcppgsl/blob/master/.travis.yml))
- install all required CRAN packags as r-cran-* binaries (and I have checked they all exist in Michael's PPA).

[ Now, I don't mean to impose "my" style here. I am happy with this older / existing / maintained (by me) setup but I am of course aware that most of the world moved to another format (see the official Travis docs).  I don't use that, but you are of course free to switch. I just can't help. ]

With the disclaimer out of the way, happy to support/update the existing one.  Or not if you feel what is there now is good enough.

**Comment by dwarton** [comment]
Hi Dirk,
sounds fine with me, if you want to do this then by all means go for it
all the best
David

**Comment by eddelbuettel** [comment]
Thanks, @dwarton -- it is there now as #60.  Based on a sample of size one [yay, science ;-) ] the travis run seems a little quicker as we get more packages pre-installed.
