### ISSUE TITLE
block function in anova/summary

### ISSUE THREAD

**Issue by johnWilshire** [dwarton/mvabund#61]
From a forwarded email of Davids to Julian: 
"
There is a block function in manyglm.  I would like to:
-  Extend it to manylm
-  Remove the error “needs to be balanced” if resamp=”case”
"

**Comment by johnWilshire** [comment]
@dwarton There is no block function in  the `summary.many[g]lm`,

Did you want it to be added in the same way as the `anova.manyglm`?

**Comment by dwarton** [comment]
sure

**Comment by johnWilshire** [comment]
#56 should resolve this

**Comment by johnWilshire** [comment]
From an email of Davids to Julian:
1. The block argument on anova.manyglm currently returns an error when the blocking factor is not balanced.  E.g. for attached dataset

```r
ft.estu = manyglm(Total~Mod,data=estuarySmall)
an.estu = anova(ft.estu,block=estuarySmall$Estuary,resamp="case")
```
The error reads
`Sorry, block needs to be a balanced factor - same number of rows for each level`
It should however work if resamp=”case” and should otherwise return the error message
 `Sorry, unless you are using case resampling, block needs to be a balanced factor - same number of rows for each level. Try using resamp=”case”.`



2. It seems the block argument was only coded for anova.manyglm, but not for manylm.  Can you please extend it to that case too, so that the following works:
```r
ft.estu = manylm(Total~Mod,data=estuarySmall)
an.estu = anova(ft.estu,block=estuarySmall$Estuary,resamp="case")
```
I think from memory the block argument was specified in R not C, and it is fairly generically written, so that should be easy.

---

3. The case resampling argument does not work properly for manylm.  This problem might not be easy to fix, but is important!  This is how it is supposed to work:


```r
nsim=100
ps=rep(NA,nsim)
gen = function(scaling) {
   rpois(length(estuarySmall$Total),lambda=1+scaling*as.numeric(estuarySmall$Mod))
}
for(i in 1:nsim){
    estuarySmall$TotalSim=gen(0)
    ft.estu = manyglm(TotalSim~Mod,data=estuarySmall)
    ps[i] = anova(ft.estu,resamp="case",test="wald")$table[2,4]
}

hist(ps)

nsim=100
ps1=rep(NA,nsim)
for(i in 1:nsim){
   estuarySmall$TotalSim = gen(1)
   ft.estu = manyglm(TotalSim~Mod,data=estuarySmall)
   ps1[i] = anova(ft.estu,resamp="case",test="wald")$table[2,4]
}

hist(ps1)
```

where ps is roughly uniformly distributed between 0 and 1, because the null is true, whereas ps1 is usually close to 0, on account of the null not being true.

But for linear models it all goes pear-shaped:
```r
nsim=100
ps=rep(NA,nsim)
gen = function(scaling) {
   rnorm(length(estuarySmall$Total),scaling*as.numeric(estuarySmall$Mod))
}

for(i in 1:nsim){
  estuarySmall$TotalSim = gen(0)
  ft.estu = manylm(TotalSim~Mod,data=estuarySmall)
  ps[i] = anova(ft.estu, resamp="case")$table[2,4]
}

hist(ps)
ps4=rep(NA,nsim)
for(i in 1:nsim){
  estuarySmall$TotalSim =gen(4)
  ft.estu = manylm(TotalSim~Mod,data=estuarySmall)
  ps4[i] = anova(ft.estu,resamp="case")$table[2,4]
}

hist(ps4)
```

The problem is that case resampling simulates under the alternative hypothesis,
 so we have to subtract off the original fits under the alternative to get back
  to a situation where the null hypothesis is approximately true.

So when case resampling is done, the test statistic should be computed on resampled data using

Y*-X*hat{beta} rather than on Y*, where X* is the resampled design matrix and hat{beta} is the original coefficients. 
Equivalently, we could use res* in resampling, where res are the residuals from the original model fit.
Something like this has been done in the anova.manyglm code but seemingly not for many.lm, at least, not correctly.
