### ISSUE TITLE
plot.manyglm ignoring small values

### ISSUE THREAD

**Issue by dwarton** [dwarton/mvabund#62]
plot.manyglm is ignoring small predicted values, rather than truncating them to keep them on the plot.  In default.plot.manyglm, lines 410-4:
      yhtmp <- c(yh)
      yh.is.zero <- yhtmp < (-6)
#       yh.is.zero <- yhtmp < max(-6,(-max(yhtmp)))#this line is wrong - it kicks out any value more negative than max(yh)
       yh0 <- yhtmp[!yh.is.zero]
should probably do something like yh0=pmax(-6,yh) instead

**Comment by johnWilshire** [comment]
Your suggestion worked: 
From the current cran version running:
removes the offending point
```r
library(mvabund)
Y <- mvabund(sapply(1:5, function(x) rpois(100, 10)))
junk <- rnorm(100)
m <- manyglm(Y ~ junk, family='poisson')
# no extremly small values
min(c(m$linear.predictor))
# kicking off large residuals
# put the yh crazy
m$linear.predictor[1,1] <- -10
plot(m)
```
<img width="603" alt="screen shot 2018-06-04 at 3 42 29 pm" src="https://user-images.githubusercontent.com/1732458/40900335-6ee0edf8-680e-11e8-8239-0e9f22199f56.png">


PR #56  just truncates it which I think is what you want: 
<img width="707" alt="screen shot 2018-06-04 at 3 43 17 pm" src="https://user-images.githubusercontent.com/1732458/40900319-5e85468e-680e-11e8-914d-ff8f63517965.png">
