### ISSUE TITLE
Obtain univariate p-values for all pairwise comparisons of factor levels in anova.manyglm

### ISSUE THREAD

**Issue by kdpaepe** [dwarton/mvabund#72]
Dear, 

I was wondering if there is a way to combine the pairwise comparison option with the p.uni="adjusted" option in anova.manyglm to obtain adjusted p-values for every response variable for every possible pairwise combination of factor levels. 

While p.uni="adjusted" or pairwise comparisons work fine when specified separately, I get the following error message when I use both arguments together: 
_Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent_

Many thanks in advance for your time and consideration.

**Comment by dwarton** [comment]
I can't replicate your issue without reproducible code but I think it is unrelated to your request - pairwise.comp and p.uni="adjusted" can both be supplied and will run.  However at the moment they are not both done at the same time - pairwise comparisons is done on the global test only
