### ISSUE TITLE
CI updates

### ISSUE THREAD

**Issue by eddelbuettel** [dwarton/mvabund#90]
The Travis CI support via file `.travis.yml` could be updated to using Ubuntu 20.04 and slightlt nicer internal logic.  

However, a bigger / more important change may be to also switch to / enable GitHub Actions. I am doing that for my repos now one-by-one because I have run out of so-called "free" credits at Travis.  This repo runs under Alice's handle and allocation so we get by with the 10,000 credits from Travis.

More details (and examples) are at https://eddelbuettel.github.io/r-ci/ -- if it helps I would be happy to simplify and improve the setup.  We can simply turn both Travis CI and GitHub Actions on (with a small update to Travis).

**Comment by dwarton** [comment]
sure if you wanted to have a crack at this that would be super

**Comment by eddelbuettel** [comment]
Sure, see PR #94 just filed.

**Comment by eddelbuettel** [comment]
Fixed by #94 which I forgot to add a `closes #90` tag to...
